name: salesmanapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version:  1.4.0+1
#version: 1.3.8+1
#version: 1.3.7+1
#version: 1.3.6+1
#version: 1.3.5+1
#version: 1.3.4+1
#version: 1.3.3+1
#version: 1.3.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  # sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  # shared_preferences: ^0.5.8
  # progress_dialog: ^1.1.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  signature: ^5.0.1
  intl: ^0.18.0
  date_format: ^2.0.6
  badges: ^3.1.1
  group_radio_button: ^1.2.0
  flutter_datetime_picker: ^1.5.1
  number_to_words: ^1.0.0
  path_provider: ^2.0.10
  reflectable: 4.0.2
  image_picker: ^0.8.5+3
  carousel_pro: ^1.0.0
  sqflite: ^2.0.2+1
  flutter_launcher_icons: ^0.9.2
  retry: ^3.1.0
  # timezone: ^0.8.0
  # device_info: ^2.0.2
  network_to_file_image: ^4.0.1
  encrypt: ^5.0.1
  # root_check: ^0.0.2+1
  archive: ^3.3.0
  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^9.2.0
  package_info: ^2.0.2
  url_launcher: ^6.1.2
  get: ^4.6.5
  avatar_view: ^1.0.1
  switcher: ^1.0.0
  dio: ^4.0.6
  page_transition: ^2.0.5
  provider: ^6.0.3
  platform: ^3.1.0
  table_calendar: ^3.0.9
  # image_picker: ^0.6.3+1
  # path_provider:
  # share: ^0.6.3+6
  # image_gallery_saver: ^1.2.2
  # permission_handler: ^4.2.0+hotfix.3
  # dio:
  shared_preferences: ^2.0.0
  flutter_carousel_slider: ^1.1.0
  currency_text_input_formatter: ^2.1.10
  money_formatter: ^0.0.4
  cool_alert: ^2.0.1
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  # adaptive_icon_background: "#FF0000" //red
  adaptive_icon_background: "#ffffff"
  adaptive_icon_padding: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      # - assets/images/add2.png
      - assets/images/dtruck.png
      - assets/images/truck.png
      - assets/images/person.png
      - assets/images/trans.png
      - assets/images/chequedefault.png
      # - assets/images/person_white.png
      # - assets/images/location.png
      # - assets/images/contact.png
      # - assets/images/changep.png
      # - assets/images/route.png
      # - assets/images/logout.png
      # - assets/images/art.png
      - assets/images/back.png
      # - assets/images/category.png
      # - assets/images/check.gif
      # - assets/images/gif1.gif
      # - assets/images/check1.gif
      - assets/images/cart2.gif
      # - assets/images/peso.png
      # - assets/images/payment.png
      # - assets/images/sign.png
      # - assets/images/wpf_name.png
      # - assets/images/cart.png
      # - assets/images/bank.png
      # - assets/images/cheque.png
      # - assets/images/cash.png
      # - assets/images/pesologo.png
      # - assets/images/no_image.png
      # - assets/images/no_image1.png
      - assets/images/wall.png
      - assets/images/rooted.png
      - assets/images/sm.png
      - assets/images/hepe.png
      - assets/images/discount.png
      # - assets/images/img1.jpg
      # - assets/images/img2.jpg
      # - assets/images/img3.jpg
      # - assets/images/img4.jpg
      # - assets/images/img5.jpg
      # - assets/images/img5.png
      - assets/images/no_image_item.jpg
      # - assets/images/dist.png
      # - assets/images/no_search.png
      # - assets/images/item.png
      # - assets/images/ldi2.png
      - assets/images/wip.png
      - assets/images/wip.gif
      - assets/2020a_2015-2025.tzf
      - assets/images/icon_red.png
      - assets/images/money.png
      - assets/principal-images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
